name: CI test
on: [push]
jobs:
  error-test:
    name: Error test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
        ./success.sh
        ./failure.sh; status=$?
        echo "After failure"
        exit $status
