name: 10 mn test
on:
  schedule:
    - cron:  '*/10 * * * *'
jobs:
  windows:
    name: Windows test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Check cached commit
      id: cache-commit
      uses: actions/cache@master
      with:
        key: ref-${{ github.sha }}
        path: ignored
    - name: Check same version
      if: steps.cache-commit.outputs.cache-hit == 'true'
      run: |
        $date = Get-Date -DisplayHint Time
        Write-Output "$date : ${{ github.sha }}: Same commit"
    - name: Check different version
      if: steps.cache-commit.outputs.cache-hit != 'true'
      run: |
        $date = Get-Date -DisplayHint Time
        Write-Output "$date : ${{ github.sha }}: Not the same commit"
