name: CI

# Trigger the workflow on push or pull request, for master branch only.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-gcc:
    name: Linux with gcc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install dos2unix curl tar libpcsclite-dev libcurl4 libcurl4-openssl-dev dpkg-dev
    - name: build
      run: make -C src
    - name: test app
      run: src/Release-x86_64/app
    - name: test app_dll
      run: src/Release-x86_64/app_dll

  linux-clang:
    name: Linux with clang
    runs-on: ubuntu-latest
    env:
      CC: clang++
      CXX: clang++
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install dos2unix curl tar libpcsclite-dev libcurl4 libcurl4-openssl-dev dpkg-dev
    - name: build
      run: make -C src
    - name: test app
      run: src/Release-x86_64/app
    - name: test app_dll
      run: src/Release-x86_64/app_dll

  macos-clang:
    name: macOS with clang
    runs-on: macos-latest
    env:
      CC: clang++
      CXX: clang++
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        brew update
        brew install gnu-sed grep dos2unix pcsc-lite
    - name: check dependencies
      run: |
        pwd
        gsed --version
        ggrep --version
        dos2unix --version
    - name: build
      run: make -C src
    - name: test app
      run: src/Release-x86_64/app
    - name: test app_dll
      run: src/Release-x86_64/app_dll

  windows-msvc:
    name: Windows with VC++
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: build 64-bit
      run: src/Build.ps1 x64
    - name: build 32-bit
      run: src/Build.ps1 Win32
    - name: test app 64-bit
      run: src/Release-x64/app.exe
    - name: test app 32-bit
      run: src/Release-Win32/app.exe
    - name: test app_dll 64-bit
      run: src/Release-x64/app_dll.exe
    - name: test app_dll 32-bit
      run: src/Release-Win32/app_dll.exe
    - name: test tsduck exec
      run: |
        pwd
        ls tsduck
        tsduck/tsversion.exe --version=all

