name: CI test
on: [push]
jobs:
  windows-test:
    name: Windows test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Display config
      run: |
        Write-Output 'github.event="${{ github.event }}"'
        Write-Output 'github.event_path="${{ github.event_path }}"'
        Write-Output 'github.workflow="${{ github.workflow }}"'
        Write-Output 'github.actor="${{ github.actor }}"'
        Write-Output 'github.repository="${{ github.repository }}"'
        Write-Output 'github.event_name="${{ github.event_name }}"'
        Write-Output 'github.sha="${{ github.sha }}"'
        Write-Output 'github.ref="${{ github.ref }}"'
        Write-Output 'github.workspace="${{ github.workspace }}"'
        Write-Output 'github.action="${{ github.action }}"'
        Write-Output 'job="${{ toJson(job) }}"'
        Write-Output 'steps="${{ toJson(steps) }}"'
        Write-Output 'runner="${{ toJson(runner) }}"'
    - name: Get previous version
      uses: actions/download-artifact@v1
      with:
        name: version
    - name: Check version
      run: |
        $version = "1.3.45"
        $previous_version = Get-Content -ErrorAction Ignore version.txt
        Write-Output "Version: previous: $previous_version, current: $version"
        Write-Output "::set-env name=VERSION::$version"
        if ($previous_version -eq $version) {
            Write-Output "Same version, don't rebuild"
            Write-Output "::set-env name=SAME_VERSION::true"
        }
    - name: Build app
      if: ${{ env.SAME_VERSION }} != ''
      run: |
        $version = "${{ env.VERSION }}"
        $version | Out-File version.txt
        "Application 32 version $version" | Out-File app32-$version.txt
        "Application 64 version $version" | Out-File app64-$version.txt
    - name: Upload version
      if: ${{ env.SAME_VERSION }} != ''
      uses: actions/upload-artifact@master
      with:
        name: version
        path: version.txt
    - name: Upload app 32
      if: ${{ env.SAME_VERSION }} != ''
      uses: actions/upload-artifact@master
      with:
        name: installer-32
        path: app32-${{ env.VERSION }}.txt
    - name: Upload app 64
      if: ${{ env.SAME_VERSION }} != ''
      uses: actions/upload-artifact@master
      with:
        name: installer-64
        path: app64-${{ env.VERSION }}.txt
