name: Test 8

on:
  workflow_run:
    workflows:
      - Test 7
    types:
      - completed

jobs:
  test:
    name: Test 8
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Workflow 7 completed" 
          date
